[package]
name = "feemultitool"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
dialoguer = "0.11.0"
grrs = "0.1.0"
image = "0.25.5"
imageproc = "0.25.0"
native-dialog = "0.7.0"
